### PR TITLE
Refactor 'Confirm Delete' dialog for Vivaldia Support

### LINKED ISSUE #3: Delete button not working
Extension version: 1.0.5
Browser: Vivaldi 2.1.1337.47, win8.1 x64

I can't delete a tab set when pressing the delete button, any hints what might be happening ?

Thanks, this one is a great extension

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #3 

Refactor 'Confirm Delete' dialog, replacing usage of vanilla js `confirm()` with a custom confirm model using [sweetalert](sweetalert.js.org).

This resolves the issue where the 'Confirm Delete' dialog was not displayed in Vivaldia due to its built-in popup blocker, thus preventing users from deleting pinned tab groups.

### CODE REVIEW

**Comment by mattyg** [comment]
### Manual Testing
- [x] Chrome 87.0.4280.88
- [x] Vivaldia 3.5.2115.81

**Comment by oraant** [comment]
Oh man, you fixed it, please relase the new version, can't wait to use it.

**Comment by mattyg** [comment]
@oraant The new version with Vivaldia support has been released to the Chrome Web Store. Please let me know if you have any questions or issues.

**Comment by oraant** [comment]
@mattyg It works! Awesome! Thanks man!!

**Pull request merged**
